replicaCount: 3

service:
  type: LoadBalancer
  serviceAnnotations:
    cloud.google.com/load-balancer-type: "Internal"

elasticsearch:
  deploy: true

properties:
  storage.backend: hbase
  storage.directory: null
  storage.hbase.ext.google.bigtable.instance.id: $INSTANCE_ID
  storage.hbase.ext.google.bigtable.project.id: $GOOGLE_CLOUD_PROJECT
  storage.hbase.ext.hbase.client.connection.impl: com.google.cloud.bigtable.hbase1_x.BigtableConnection
  index.search.backend: elasticsearch
  index.search.directory: null
  cache.db-cache: true
  cache.db-cache-clean-wait: 20
  cache.db-cache-time: 180000
  cache.db-cache-size: 0.5

persistence:
  enabled: false
